#!/bin/sh

cd $HOME

# No thank you
rm -rf .oh-my-bash
rm -rf .oh-my-zsh
rm .zshrc

sudo apt-get install -y fish pick neovim tmux ruby curl git jq

sudo gem install tmuxinator

chsh -s /usr/bin/fish

