#!/bin/sh

sudo rm -rf ~/.oh-my-bash
sudo rm -rf ~/.oh-my-zsh
sudo rm ~/.zshrc

sudo apt-get install -y fish pick neovim tmux ruby curl git jq ripgrep

echo "Copying dotfiles.."
cp -r /workspaces/.codespaces/.persistedshare/dotfiles/.config/ ~/
cp /workspaces/.codespaces/.persistedshare/dotfiles/.tmux.conf ~/

# Install Neovim plugin manager
curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install Neovim plugins
nvim -es -u init.vim -i NONE -c "PlugInstall" -c "qa"

echo "Setting default shell to fish.."
sudo chsh -s /usr/bin/fish
