#!/bin/sh

sudo rm -rf ~/.oh-my-bash
sudo rm -rf ~/.oh-my-zsh
sudo rm ~/.zshrc

sudo apt-get install -y fish pick neovim tmux ruby curl git jq ripgrep

cp -r /workspaces/.codespaces/.persistedshare/dotfiles/.config/ ~/

chsh -s /usr/bin/fish
